# Generated by Django 4.1 on 2022-08-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id_clima', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('temp', models.IntegerField(blank=True, null=True)),
                ('wind_speed', models.IntegerField(blank=True, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=20, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id_log', models.IntegerField(primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
